"""add email_action_history table

Revision ID: 18db2440cd0b
Revises: 299901b6bb7d
Create Date: 2026-03-10 17:00:35.630463

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18db2440cd0b'
down_revision: str | None = '299901b6bb7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_action_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classified_email_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classified_email_id'], ['classified_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_action_history_email_id', 'email_action_history', ['classified_email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_action_history_email_id', table_name='email_action_history')
    op.drop_table('email_action_history')
    # ### end Alembic commands ###
