"""add analysis_type to analyses

Revision ID: 299901b6bb7d
Revises: b2c3d4e5f6g7
Create Date: 2026-03-10 16:16:38.082924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299901b6bb7d'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('analysis_type', sa.String(length=20), nullable=False, server_default='ai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'analysis_type')
    # ### end Alembic commands ###
