"""add ai_insights to analyses

Revision ID: f80622ade508
Revises: 143f67a90b1a
Create Date: 2026-03-11 11:18:58.015550

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f80622ade508'
down_revision: Union[str, None] = '143f67a90b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('ai_insights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'ai_insights')
    # ### end Alembic commands ###
